# Model arguments
# model_name_or_path: /home/jerome/GAPO/outputs/mistral-7b-instruct-gapo_noise_len_0.2/checkpoint-466
model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2
torch_dtype: null
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  princeton-nlp/mistral-instruct-ultrafeedback: 1.0
  # datasets/mistral_len_0.2_reverse: 1.0

dataset_splits:
- train
- test
preprocessing_num_workers: 12

# GAPOTrainer arguments
bf16: true
beta: 2.5
gamma_beta_ratio: 0.1
do_eval: true
rho: 0.05
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 64
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: gapo-exps
learning_rate: 5.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
output_dir: outputs/mistral-7b-instruct-gapo_grad
run_name: mistral-7b-instruct-gapo
per_device_train_batch_size: 1
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "steps"
# perturb_start_layer: 24

save_steps: 116
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
