# Model arguments
model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2
torch_dtype: auto
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  /home/jerome/GAPO/datasets/mistral_intruct_0.2: 1.0

dataset_splits:
- train
- test
preprocessing_num_workers: 12

# EpsilonDPOTrainer arguments
bf16: true
beta: 0.01
epsilon: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: edpo-exps
learning_rate: 3.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
output_dir: outputs/mistral-7b-instruct-edpo_rn0.2_fix
run_name: s2_edpo_rn0.2_fix_fix
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "steps"
save_steps: 116
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
